repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: bash -c "cd python_coderunner && ruff check src/ tests/"
        language: system
        types: [python]

      - id: ruff_format
        name: ruff_format
        # not in args, because entry is bash
        entry: bash -c "cd python_coderunner && ruff format --quiet"
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: bash -c "cd python_coderunner && isort src/ tests/"
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: bash -c "cd python_coderunner && mypy src/ tests/"
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: bash -c "cd python_coderunner && pylint src/ tests/"
        language: system
        types: [python]
