repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: bash -c "cd python && ruff check src/ tests/"
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: bash -c "cd python && isort src/ tests/"
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: bash -c "cd python && mypy src/ tests/"
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: bash -c "cd python && pylint src/ tests/"
        language: system
        types: [python]
