from abc import ABC, abstractmethod


class ICommandBuilder(ABC):
    @abstractmethod
    def build(self, file_path_abs: str) -> str:
        """
        Build requires absolute file path, because file can be temporary,
        like file which was generated by run selected.
        """
        raise NotImplementedError
