import os
import typing

from src.file_info_extractor.interface import IFileInfoExtractor


class TBasicFileInfoExtractor(IFileInfoExtractor):
    def get_workspace_root(self, file_path_abs: str) -> str:
        """Dummy implementation: returns the directory of the current file."""
        return os.path.dirname(file_path_abs)

    def get_dir(self, file_path_abs: str) -> str:
        dir_path: str = os.path.dirname(file_path_abs)
        if dir_path and not dir_path.endswith(os.sep):
            dir_path += os.sep
        return dir_path

    def get_dir_without_trailing_slash(self, file_path_abs: str) -> str:
        return os.path.dirname(file_path_abs).rstrip(os.sep)

    def get_file_name(self, file_path_abs: str) -> str:
        return os.path.basename(file_path_abs)

    def get_file_name_without_ext(self, file_path_abs: str) -> str:
        base: str = self.get_file_name(file_path_abs)
        dot_pos: int = base.find(".")
        return base[:dot_pos] if dot_pos != -1 else base

    def get_file_ext(self, file_path_abs: str) -> str:
        base: str = self.get_file_name(file_path_abs)
        dot_pos: int = base.find(".")
        return (base[dot_pos : len(base)] if dot_pos != -1 else "").lower()

    def get_file_type(self, file_path_abs: str) -> typing.Optional[str]:
        return self.EXT_TO_LANG.get(self.get_file_ext(file_path_abs))

    def get_full_file_name(self, file_path_abs: str) -> typing.Optional[str]:
        return file_path_abs

    def get_drive_letter(self, file_path_abs: str) -> str:
        drive, _ = os.path.splitdrive(file_path_abs)
        return drive

    EXT_TO_LANG: typing.Final[typing.Dict[str, str]] = {
        ".4dm": "4D",
        ".4gl": "Genero 4gl",
        ".4th": "Forth",
        ".6pl": "Raku",
        ".6pm": "Raku",
        ".8xp": "TI Program",
        ".8xp.txt": "TI Program",
        "._coffee": "CoffeeScript",
        "._js": "JavaScript",
        "._ls": "LiveScript",
        ".a51": "Assembly",
        ".abap": "ABAP",
        ".ada": "Ada",
        ".adb": "Ada",
        ".ado": "Stata",
        ".adp": "Tcl",
        ".ads": "Ada",
        ".agc": "Apollo Guidance Computer",
        ".agda": "Agda",
        ".ahk": "AutoHotkey",
        ".ahkl": "AutoHotkey",
        ".aidl": "AIDL",
        ".aj": "AspectJ",
        ".al": "Perl",
        ".als": "Alloy",
        ".ampl": "AMPL",
        ".angelscript": "AngelScript",
        ".apex": "Apex",
        ".apl": "APL",
        ".app": "Erlang",
        ".app.src": "Erlang",
        ".applescript": "AppleScript",
        ".arc": "Arc",
        ".arr": "Pyret",
        ".as": "AngelScript",
        ".asax": "ASP.NET",
        ".asc": "AGS Script",
        ".ascx": "ASP.NET",
        ".asd": "Common Lisp",
        ".asddls": "ABAP CDS",
        ".ash": "AGS Script",
        ".ashx": "ASP.NET",
        ".asl": "ASL",
        ".asm": "Motorola 68K Assembly",
        ".asmx": "ASP.NET",
        ".asp": "Classic ASP",
        ".aspx": "ASP.NET",
        ".asy": "Asymptote",
        ".au3": "AutoIt",
        ".aug": "Augeas",
        ".auk": "Awk",
        ".aw": "PHP",
        ".awk": "Awk",
        ".axd": "ASP.NET",
        ".axi": "NetLinx",
        ".axi.erb": "NetLinx+ERB",
        ".axs": "NetLinx",
        ".axs.erb": "NetLinx+ERB",
        ".b": "Limbo",
        ".bal": "Ballerina",
        ".bas": "Visual Basic 6.0",
        ".bash": "Shell",
        ".bat": "Batchfile",
        ".bats": "Shell",
        ".bb": "Clojure",
        ".bbappend": "BitBake",
        ".bbclass": "BitBake",
        ".bdy": "PLSQL",
        ".be": "Berry",
        ".befunge": "Befunge",
        ".bf": "HyPhy",
        ".bi": "FreeBASIC",
        ".bicep": "Bicep",
        ".bicepparam": "Bicep",
        ".bison": "Bison",
        ".bmx": "BlitzMax",
        ".bones": "JavaScript",
        ".boo": "Boo",
        ".boot": "Clojure",
        ".bpl": "Boogie",
        ".bqn": "BQN",
        ".bro": "Zeek",
        ".brs": "Brightscript",
        ".bs": "BrighterScript",
        ".bsl": "1C Enterprise",
        ".bst": "BibTeX Style",
        ".bsv": "Bluespec",
        ".builder": "Ruby",
        ".bzl": "Starlark",
        ".c": "C",
        ".c++": "C++",
        ".cairo": "Cairo Zero",
        ".cake": "CoffeeScript",
        ".capnp": "Cap'n Proto",
        ".carbon": "Carbon",
        ".cats": "C",
        ".cbl": "COBOL",
        ".cc": "C++",
        ".ccp": "COBOL",
        ".cdc": "Cadence",
        ".cdf": "Mathematica",
        ".cds": "CAP CDS",
        ".ceylon": "Ceylon",
        ".cfc": "ColdFusion CFC",
        ".cfm": "ColdFusion",
        ".cfml": "ColdFusion",
        ".cgi": "Shell",
        ".cginc": "HLSL",
        ".ch": "xBase",
        ".chpl": "Chapel",
        ".chs": "C2hs Haskell",
        ".circom": "Circom",
        ".cirru": "Cirru",
        ".cjs": "JavaScript",
        ".cjsx": "CoffeeScript",
        ".ck": "ChucK",
        ".cl": "OpenCL",
        ".cl2": "Clojure",
        ".clar": "Clarity",
        ".click": "Click",
        ".clj": "Clojure",
        ".cljc": "Clojure",
        ".cljs": "Clojure",
        ".cljs.hl": "Clojure",
        ".cljscm": "Clojure",
        ".cljx": "Clojure",
        ".clp": "CLIPS",
        ".cls": "Visual Basic 6.0",
        ".clw": "Clarion",
        ".cmake": "CMake",
        ".cmake.in": "CMake",
        ".cmd": "Batchfile",
        ".cnc": "G-code",
        ".cob": "COBOL",
        ".cobol": "COBOL",
        ".cocci": "SmPL",
        ".coffee": "CoffeeScript",
        ".coffee.md": "Literate CoffeeScript",
        ".com": "DIGITAL Command Language",
        ".command": "Shell",
        ".containerfile": "Dockerfile",
        ".coq": "Rocq Prover",
        ".cp": "Component Pascal",
        ".cpp": "C++",
        ".cppm": "C++",
        ".cps": "Component Pascal",
        ".cpy": "COBOL",
        ".cr": "Crystal",
        ".cs": "Smalltalk",
        ".cs.pp": "C#",
        ".csc": "GSC",
        ".csd": "Csound Document",
        ".csh": "Tcsh",
        ".csx": "C#",
        ".ctl": "Visual Basic 6.0",
        ".ctp": "PHP",
        ".cts": "TypeScript",
        ".cu": "Cuda",
        ".cue": "CUE",
        ".cuh": "Cuda",
        ".curry": "Curry",
        ".cw": "Redcode",
        ".cwl": "Common Workflow Language",
        ".cxx": "C++",
        ".cy": "Cycript",
        ".cyp": "Cypher",
        ".cypher": "Cypher",
        ".d": "Makefile",
        ".dart": "Dart",
        ".dats": "ATS",
        ".db2": "SQLPL",
        ".dcl": "Clean",
        ".ddl": "PLSQL",
        ".decls": "BlitzBasic",
        ".dfm": "Pascal",
        ".dfy": "Dafny",
        ".dhall": "Dhall",
        ".di": "D",
        ".djs": "Dogescript",
        ".dlm": "IDL",
        ".dm": "DM",
        ".do": "Stata",
        ".dockerfile": "Dockerfile",
        ".doh": "Stata",
        ".dpr": "Pascal",
        ".druby": "Mirah",
        ".dsc": "DenizenScript",
        ".dsl": "ASL",
        ".dsp": "Faust",
        ".dsr": "Visual Basic 6.0",
        ".duby": "Mirah",
        ".dwl": "DataWeave",
        ".dyalog": "APL",
        ".dyl": "Dylan",
        ".dylan": "Dylan",
        ".e": "Euphoria",
        ".ebuild": "Gentoo Ebuild",
        ".ec": "eC",
        ".ecl": "ECLiPSe",
        ".eclass": "Gentoo Eclass",
        ".eclxml": "ECL",
        ".edgeql": "EdgeQL",
        ".eh": "eC",
        ".el": "Emacs Lisp",
        ".eliom": "OCaml",
        ".eliomi": "OCaml",
        ".elm": "Elm",
        ".elv": "Elvish",
        ".em": "EmberScript",
        ".emacs": "Emacs Lisp",
        ".emacs.desktop": "Emacs Lisp",
        ".emberscript": "EmberScript",
        ".eq": "EQ",
        ".erl": "Erlang",
        ".es": "JavaScript",
        ".es6": "JavaScript",
        ".escript": "Erlang",
        ".esdl": "EdgeQL",
        ".ex": "Euphoria",
        ".exs": "Elixir",
        ".eye": "Ruby",
        ".f": "Fortran",
        ".f03": "Fortran Free Form",
        ".f08": "Fortran Free Form",
        ".f77": "Fortran",
        ".f90": "Fortran Free Form",
        ".f95": "Fortran Free Form",
        ".factor": "Factor",
        ".fan": "Fantom",
        ".fancypack": "Fancy",
        ".fcgi": "Shell",
        ".feature": "Gherkin",
        ".fir": "FIRRTL",
        ".fish": "fish",
        ".flex": "JFlex",
        ".flux": "FLUX",
        ".fnc": "PLSQL",
        ".fnl": "Fennel",
        ".for": "Fortran",
        ".forth": "Forth",
        ".fp": "GLSL",
        ".fpp": "Fortran",
        ".fr": "Frege",
        ".frag": "JavaScript",
        ".frg": "GLSL",
        ".frm": "Visual Basic 6.0",
        ".frt": "Forth",
        ".fs": "GLSL",
        ".fsh": "GLSL",
        ".fshader": "GLSL",
        ".fsi": "F#",
        ".fst": "F*",
        ".fsti": "F*",
        ".fsx": "F#",
        ".fth": "Forth",
        ".ftl": "FreeMarker",
        ".fun": "Standard ML",
        ".fut": "Futhark",
        ".fx": "HLSL",
        ".fxh": "HLSL",
        ".fy": "Fancy",
        ".g": "GAP",
        ".g4": "ANTLR",
        ".gaml": "GAML",
        ".gap": "GAP",
        ".gawk": "Awk",
        ".gco": "G-code",
        ".gcode": "G-code",
        ".gd": "GDScript",
        ".gdb": "GDB",
        ".gdbinit": "GDB",
        ".gemspec": "Ruby",
        ".geo": "GLSL",
        ".geom": "GLSL",
        ".gf": "Grammatical Framework",
        ".gi": "GAP",
        ".gjs": "Glimmer JS",
        ".gleam": "Gleam",
        ".glf": "Glyph",
        ".glsl": "GLSL",
        ".glslf": "GLSL",
        ".glslv": "GLSL",
        ".gml": "Game Maker Language",
        ".gms": "GAMS",
        ".gnu": "Gnuplot",
        ".gnuplot": "Gnuplot",
        ".go": "Go",
        ".god": "Ruby",
        ".golo": "Golo",
        ".gp": "Gnuplot",
        ".grace": "Grace",
        ".groovy": "Groovy",
        ".grt": "Groovy",
        ".gs": "JavaScript",
        ".gsc": "GSC",
        ".gsh": "GSC",
        ".gshader": "GLSL",
        ".gsp": "Groovy Server Pages",
        ".gst": "Gosu",
        ".gsx": "Gosu",
        ".gtpl": "Groovy",
        ".gts": "Glimmer TS",
        ".gvy": "Groovy",
        ".gyp": "Python",
        ".gypi": "Python",
        ".h": "Objective-C",
        ".h++": "C++",
        ".h.in": "C",
        ".ha": "Hare",
        ".hack": "Hack",
        ".hats": "ATS",
        ".hb": "Harbour",
        ".hc": "HolyC",
        ".hcl": "HCL",
        ".hh": "Hack",
        ".hhi": "Hack",
        ".hic": "Clojure",
        ".hip": "HIP",
        ".hlean": "Lean",
        ".hlsl": "HLSL",
        ".hlsli": "HLSL",
        ".hoon": "hoon",
        ".hpp": "C++",
        ".hqf": "SQF",
        ".hql": "HiveQL",
        ".hrl": "Erlang",
        ".hs": "Haskell",
        ".hs-boot": "Haskell",
        ".hsc": "Haskell",
        ".hx": "Haxe",
        ".hxsl": "Haxe",
        ".hxx": "C++",
        ".hy": "Hy",
        ".i": "SWIG",
        ".i3": "Modula-3",
        ".i7x": "Inform 7",
        ".ice": "Slice",
        ".iced": "CoffeeScript",
        ".icl": "Clean",
        ".idc": "C",
        ".idr": "Idris",
        ".ig": "Modula-3",
        ".ihlp": "Stata",
        ".ijm": "ImageJ Macro",
        ".ijs": "J",
        ".ik": "Ioke",
        ".ily": "LilyPond",
        ".imba": "Imba",
        ".inc": "SourcePawn",
        ".ink": "Ink",
        ".inl": "C++",
        ".ino": "C++",
        ".intr": "Dylan",
        ".io": "Io",
        ".iol": "Jolie",
        ".ipf": "IGOR Pro",
        ".ipp": "C++",
        ".isl": "Inno Setup",
        ".ispc": "ISPC",
        ".iss": "Inno Setup",
        ".ixx": "C++",
        ".j": "Objective-J",
        ".jai": "Jai",
        ".jake": "JavaScript",
        ".janet": "Janet",
        ".jav": "Java",
        ".java": "Java",
        ".javascript": "JavaScript",
        ".jbuilder": "Ruby",
        ".jcl": "JCL",
        ".jflex": "JFlex",
        ".jison": "Jison",
        ".jisonlex": "Jison Lex",
        ".jl": "Julia",
        ".jq": "jq",
        ".js": "JavaScript",
        ".js.erb": "JavaScript+ERB",
        ".jsb": "JavaScript",
        ".jscad": "JavaScript",
        ".jsfl": "JavaScript",
        ".jsh": "Java",
        ".jslib": "JavaScript",
        ".jsm": "JavaScript",
        ".jsonnet": "Jsonnet",
        ".jsp": "Java Server Pages",
        ".jspre": "JavaScript",
        ".jss": "JavaScript",
        ".jsx": "JavaScript",
        ".jte": "Java Template Engine",
        ".just": "Just",
        ".kak": "KakouneScript",
        ".kid": "Genshi",
        ".kk": "Koka",
        ".kojo": "Scala",
        ".krl": "KRL",
        ".ks": "KerboScript",
        ".ksh": "Shell",
        ".ksy": "Kaitai Struct",
        ".kt": "Kotlin",
        ".ktm": "Kotlin",
        ".kts": "Kotlin",
        ".l": "PicoLisp",
        ".lagda": "Literate Agda",
        ".las": "Lasso",
        ".lasso": "Lasso",
        ".lasso8": "Lasso",
        ".lasso9": "Lasso",
        ".ld": "Linker Script",
        ".lds": "Linker Script",
        ".lean": "Lean 4",
        ".lex": "Lex",
        ".lfe": "LFE",
        ".lgt": "Logtalk",
        ".lhs": "Literate Haskell",
        ".libsonnet": "Jsonnet",
        ".lid": "Dylan",
        ".lidr": "Idris",
        ".ligo": "LigoLANG",
        ".linq": "C#",
        ".lisp": "NewLisp",
        ".litcoffee": "Literate CoffeeScript",
        ".livecodescript": "LiveCode Script",
        ".lkml": "LookML",
        ".ll": "LLVM",
        ".lmi": "Python",
        ".logtalk": "Logtalk",
        ".lol": "LOLCODE",
        ".lookml": "LookML",
        ".lp": "Linear Programming",
        ".lpr": "Pascal",
        ".ls": "LoomScript",
        ".lsl": "LSL",
        ".lslp": "LSL",
        ".lsp": "NewLisp",
        ".lua": "Lua",
        ".luau": "Luau",
        ".lvclass": "LabVIEW",
        ".lvlib": "LabVIEW",
        ".lvproj": "LabVIEW",
        ".ly": "LilyPond",
        ".m": "Objective-C",
        ".m2": "Macaulay2",
        ".m3": "Modula-3",
        ".m4": "M4Sugar",
        ".ma": "Mathematica",
        ".mak": "Makefile",
        ".make": "Makefile",
        ".makefile": "Makefile",
        ".mako": "Mako",
        ".mao": "Mako",
        ".mata": "Stata",
        ".matah": "Stata",
        ".mathematica": "Mathematica",
        ".matlab": "MATLAB",
        ".mawk": "Awk",
        ".maxhelp": "Max",
        ".maxpat": "Max",
        ".maxproj": "Max",
        ".mbt": "MoonBit",
        ".mc": "Monkey C",
        ".mcfunction": "mcfunction",
        ".mcr": "MAXScript",
        ".md": "GCC Machine Description",
        ".metal": "Metal",
        ".mg": "Modula-3",
        ".minid": "MiniD",
        ".mint": "Mint",
        ".mirah": "Mirah",
        ".mjs": "JavaScript",
        ".mk": "Makefile",
        ".mkfile": "Makefile",
        ".ml": "Standard ML",
        ".ml4": "OCaml",
        ".mli": "OCaml",
        ".mligo": "CameLIGO",
        ".mlir": "MLIR",
        ".mll": "OCaml",
        ".mly": "OCaml",
        ".mm": "Objective-C++",
        ".mmk": "Module Management System",
        ".mms": "Module Management System",
        ".mo": "Motoko",
        ".mod": "NMODL",
        ".mojo": "Mojo",
        ".monkey": "Monkey",
        ".monkey2": "Monkey",
        ".moo": "Moocode",
        ".moon": "MoonScript",
        ".move": "Move",
        ".mpl": "JetBrains MPS",
        ".mps": "JetBrains MPS",
        ".mq4": "MQL4",
        ".mq5": "MQL5",
        ".mqh": "MQL5",
        ".mrc": "mIRC Script",
        ".ms": "Unix Assembly",
        ".msd": "JetBrains MPS",
        ".msg": "OMNeT++ MSG",
        ".mspec": "Ruby",
        ".mss": "CartoCSS",
        ".mt": "Mathematica",
        ".mts": "TypeScript",
        ".mu": "mupad",
        ".mud": "ZIL",
        ".muf": "MUF",
        ".mumps": "M",
        ".mxt": "Max",
        ".myt": "Myghty",
        ".mzn": "MiniZinc",
        ".n": "Nemerle",
        ".nas": "Nasal",
        ".nasl": "NASL",
        ".nasm": "Assembly",
        ".nawk": "Awk",
        ".nb": "Mathematica",
        ".nbp": "Mathematica",
        ".nc": "nesC",
        ".ncl": "NCL",
        ".ne": "Nearley",
        ".nearley": "Nearley",
        ".ned": "OMNeT++ NED",
        ".nf": "Nextflow",
        ".ni": "Inform 7",
        ".nim": "Nim",
        ".nim.cfg": "Nim",
        ".nimble": "Nim",
        ".nimrod": "Nim",
        ".nims": "Nim",
        ".nit": "Nit",
        ".nix": "Nix",
        ".njs": "JavaScript",
        ".nl": "NewLisp",
        ".nlogo": "NetLogo",
        ".nomad": "HCL",
        ".nqp": "Raku",
        ".nr": "Noir",
        ".nse": "Lua",
        ".nsh": "NSIS",
        ".nsi": "NSIS",
        ".nss": "NWScript",
        ".nu": "Nushell",
        ".numpy": "NumPy",
        ".numpyw": "NumPy",
        ".numsc": "NumPy",
        ".nut": "Squirrel",
        ".ny": "Common Lisp",
        ".ob2": "Oberon",
        ".odin": "Odin",
        ".ol": "Jolie",
        ".omgrofl": "Omgrofl",
        ".ooc": "ooc",
        ".opa": "Opa",
        ".opal": "Opal",
        ".opencl": "OpenCL",
        ".orc": "Csound",
        ".os": "1C Enterprise",
        ".overpassql": "OverpassQL",
        ".ox": "Ox",
        ".oxh": "Ox",
        ".oxo": "Ox",
        ".oxygene": "Oxygene",
        ".oz": "Oz",
        ".p": "OpenEdge ABL",
        ".p4": "P4",
        ".p6": "Raku",
        ".p6l": "Raku",
        ".p6m": "Raku",
        ".p8": "Lua",
        ".pac": "JavaScript",
        ".pact": "Pact",
        ".pan": "Pan",
        ".parrot": "Parrot",
        ".pas": "Pascal",
        ".pascal": "Pascal",
        ".pasm": "Parrot Assembly",
        ".pat": "Max",
        ".pb": "PureBasic",
        ".pbi": "PureBasic",
        ".pbt": "PowerBuilder",
        ".pck": "PLSQL",
        ".pd_lua": "Lua",
        ".pddl": "PDDL",
        ".pde": "Processing",
        ".peggy": "PEG.js",
        ".pegjs": "PEG.js",
        ".pep": "Pep8",
        ".perl": "Perl",
        ".pgsql": "PLpgSQL",
        ".ph": "Perl",
        ".php": "PHP",
        ".php3": "PHP",
        ".php4": "PHP",
        ".php5": "PHP",
        ".phps": "PHP",
        ".phpt": "PHP",
        ".pig": "PigLatin",
        ".pike": "Pike",
        ".pir": "Parrot Internal Representation",
        ".pkb": "PLSQL",
        ".pkl": "Pkl",
        ".pks": "PLSQL",
        ".pl": "Raku",
        ".pl6": "Raku",
        ".plb": "PLSQL",
        ".plot": "Gnuplot",
        ".pls": "PLSQL",
        ".plsql": "PLSQL",
        ".plt": "Prolog",
        ".pluginspec": "Ruby",
        ".plx": "Perl",
        ".pm": "Raku",
        ".pm6": "Raku",
        ".pml": "Promela",
        ".pmod": "Pike",
        ".podsl": "Common Lisp",
        ".podspec": "Ruby",
        ".pogo": "PogoScript",
        ".polar": "Polar",
        ".pony": "Pony",
        ".por": "Portugol",
        ".pov": "POV-Ray SDL",
        ".pp": "Puppet",
        ".pprx": "REXX",
        ".praat": "Praat",
        ".prawn": "Ruby",
        ".prc": "PLSQL",
        ".prg": "xBase",
        ".pri": "QMake",
        ".pro": "QMake",
        ".prolog": "Prolog",
        ".prw": "xBase",
        ".ps1": "PowerShell",
        ".psc": "Papyrus",
        ".psd1": "PowerShell",
        ".psgi": "Perl",
        ".psm1": "PowerShell",
        ".purs": "PureScript",
        ".pwn": "Pawn",
        ".pxd": "Cython",
        ".pxi": "Cython",
        ".py": "Python",
        ".py3": "Python",
        ".pyde": "Python",
        ".pyi": "Python",
        ".pyp": "Python",
        ".pyt": "Python",
        ".pyw": "Python",
        ".pyx": "Cython",
        ".q": "q",
        ".qasm": "OpenQASM",
        ".qbs": "QML",
        ".ql": "CodeQL",
        ".qll": "CodeQL",
        ".qml": "QML",
        ".qs": "Qt Script",
        ".r": "Rez",
        ".r2": "Rebol",
        ".r3": "Rebol",
        ".rabl": "Ruby",
        ".rake": "Ruby",
        ".raku": "Raku",
        ".rakumod": "Raku",
        ".rb": "Ruby",
        ".rbbas": "REALbasic",
        ".rbfrm": "REALbasic",
        ".rbi": "Ruby",
        ".rbmnu": "REALbasic",
        ".rbres": "REALbasic",
        ".rbtbar": "REALbasic",
        ".rbuild": "Ruby",
        ".rbuistate": "REALbasic",
        ".rbw": "Ruby",
        ".rbx": "Ruby",
        ".rbxs": "Lua",
        ".rchit": "GLSL",
        ".rd": "R",
        ".re": "Reason",
        ".reb": "Rebol",
        ".rebol": "Rebol",
        ".red": "Red",
        ".reds": "Red",
        ".rego": "Open Policy Agent",
        ".rei": "Reason",
        ".religo": "ReasonLIGO",
        ".res": "ReScript",
        ".resource": "RobotFramework",
        ".rex": "REXX",
        ".rexx": "REXX",
        ".rg": "Rouge",
        ".ring": "Ring",
        ".rkt": "Racket",
        ".rktd": "Racket",
        ".rktl": "Racket",
        ".rl": "Ragel",
        ".rmiss": "GLSL",
        ".robot": "RobotFramework",
        ".roc": "Roc",
        ".rockspec": "Lua",
        ".rpgle": "RPGLE",
        ".rpy": "Ren'Py",
        ".rs": "Rust",
        ".rs.in": "Rust",
        ".rsc": "RouterOS Script",
        ".rsh": "RenderScript",
        ".rsx": "R",
        ".ru": "Ruby",
        ".ruby": "Ruby",
        ".s": "Unix Assembly",
        ".sage": "Sage",
        ".sagews": "Sage",
        ".sail": "Sail",
        ".sas": "SAS",
        ".sats": "ATS",
        ".sbt": "Scala",
        ".sc": "SuperCollider",
        ".scad": "OpenSCAD",
        ".scala": "Scala",
        ".scd": "SuperCollider",
        ".sce": "Scilab",
        ".scenic": "Scenic",
        ".sch": "Scheme",
        ".sci": "Scilab",
        ".scm": "Tree-sitter Query",
        ".sco": "Csound Score",
        ".scpt": "AppleScript",
        ".scrbl": "Racket",
        ".sdc": "Tcl",
        ".sed": "sed",
        ".self": "Self",
        ".sexp": "Common Lisp",
        ".sh": "Shell",
        ".sh-session": "ShellSession",
        ".sh.in": "Shell",
        ".shader": "ShaderLab",
        ".shen": "Shen",
        ".sieve": "Sieve",
        ".sig": "Standard ML",
        ".sj": "Objective-J",
        ".sjs": "JavaScript",
        ".sl": "Slash",
        ".slang": "Slang",
        ".sld": "Scheme",
        ".sls": "Scheme",
        ".sma": "Pawn",
        ".smali": "Smali",
        ".smithy": "Smithy",
        ".smk": "Snakemake",
        ".sml": "Standard ML",
        ".smt": "SMT",
        ".smt2": "SMT",
        ".snakefile": "Snakemake",
        ".sol": "Solidity",
        ".sp": "SourcePawn",
        ".spc": "PLSQL",
        ".spec": "Ruby",
        ".spin": "Propeller Spin",
        ".sps": "Scheme",
        ".sqf": "SQF",
        ".sql": "TSQL",
        ".sqlrpgle": "RPGLE",
        ".sra": "PowerBuilder",
        ".sru": "PowerBuilder",
        ".srw": "PowerBuilder",
        ".ss": "Scheme",
        ".ssjs": "JavaScript",
        ".st": "Smalltalk",
        ".stan": "Stan",
        ".star": "Starlark",
        ".sthlp": "Stata",
        ".story": "Gherkin",
        ".sv": "SystemVerilog",
        ".svh": "SystemVerilog",
        ".sw": "Sway",
        ".swift": "Swift",
        ".t": "Turing",
        ".tac": "Python",
        ".tact": "Tact",
        ".tag": "Java Server Pages",
        ".talon": "Talon",
        ".tcc": "C++",
        ".tcl": "Tcl",
        ".tcl.in": "Tcl",
        ".tcsh": "Tcsh",
        ".tesc": "GLSL",
        ".tese": "GLSL",
        ".tf": "HCL",
        ".tfvars": "HCL",
        ".thor": "Ruby",
        ".thrift": "Thrift",
        ".thy": "Isabelle",
        ".tla": "TLA",
        ".tlv": "TL-Verilog",
        ".tm": "Tcl",
        ".tmux": "Shell",
        ".toit": "Toit",
        ".tool": "Shell",
        ".tpb": "PLSQL",
        ".tpl": "Smarty",
        ".tpp": "C++",
        ".tps": "PLSQL",
        ".trg": "PLSQL",
        ".trigger": "Shell",
        ".ts": "TypeScript",
        ".tsp": "TypeSpec",
        ".tst": "Scilab",
        ".tsx": "TSX",
        ".tu": "Turing",
        ".txl": "TXL",
        ".txx": "C++",
        ".typ": "Typst",
        ".uc": "UnrealScript",
        ".udo": "Csound",
        ".uno": "Uno",
        ".upc": "Unified Parallel C",
        ".ur": "UrWeb",
        ".urs": "UrWeb",
        ".v": "Verilog",
        ".vala": "Vala",
        ".vapi": "Vala",
        ".vark": "Gosu",
        ".vb": "Visual Basic .NET",
        ".vba": "Vim Script",
        ".vbhtml": "Visual Basic .NET",
        ".vbs": "VBScript",
        ".vcl": "VCL",
        ".veo": "Verilog",
        ".vert": "GLSL",
        ".vh": "SystemVerilog",
        ".vhd": "VHDL",
        ".vhdl": "VHDL",
        ".vhf": "VHDL",
        ".vhi": "VHDL",
        ".vho": "VHDL",
        ".vhs": "VHDL",
        ".vht": "VHDL",
        ".vhw": "VHDL",
        ".vim": "Vim Script",
        ".vimrc": "Vim Script",
        ".vmb": "Vim Script",
        ".volt": "Volt",
        ".vrx": "GLSL",
        ".vs": "GLSL",
        ".vsh": "GLSL",
        ".vshader": "GLSL",
        ".vw": "PLSQL",
        ".vy": "Vyper",
        ".w": "OpenEdge ABL",
        ".wast": "WebAssembly",
        ".wat": "WebAssembly",
        ".watchr": "Ruby",
        ".wdl": "WDL",
        ".webidl": "WebIDL",
        ".wgsl": "WGSL",
        ".whiley": "Whiley",
        ".wisp": "wisp",
        ".wl": "Mathematica",
        ".wlk": "Wollok",
        ".wlt": "Mathematica",
        ".wlua": "Lua",
        ".workflow": "HCL",
        ".wren": "Wren",
        ".ws": "Witcher Script",
        ".wsgi": "Python",
        ".x": "RPC",
        ".x10": "X10",
        ".x68": "Motorola 68K Assembly",
        ".xc": "XC",
        ".xdc": "Tcl",
        ".xi": "Logos",
        ".xm": "Logos",
        ".xojo_code": "Xojo",
        ".xojo_menu": "Xojo",
        ".xojo_report": "Xojo",
        ".xojo_script": "Xojo",
        ".xojo_toolbar": "Xojo",
        ".xojo_window": "Xojo",
        ".xpl": "XProc",
        ".xproc": "XProc",
        ".xpy": "Python",
        ".xq": "XQuery",
        ".xql": "XQuery",
        ".xqm": "XQuery",
        ".xquery": "XQuery",
        ".xqy": "XQuery",
        ".xrl": "Erlang",
        ".xs": "XS",
        ".xsh": "Xonsh",
        ".xsjs": "JavaScript",
        ".xsjslib": "JavaScript",
        ".xsl": "XSLT",
        ".xslt": "XSLT",
        ".xtend": "Xtend",
        ".xzap": "ZAP",
        ".y": "Yacc",
        ".yacc": "Yacc",
        ".yap": "Prolog",
        ".yar": "YARA",
        ".yara": "YARA",
        ".yrl": "Erlang",
        ".yul": "Yul",
        ".yy": "Yacc",
        ".z3": "SMT",
        ".zap": "ZAP",
        ".zeek": "Zeek",
        ".zep": "Zephir",
        ".zig": "Zig",
        ".zig.zon": "Zig",
        ".zil": "ZIL",
        ".zimpl": "Zimpl",
        ".zmpl": "Zimpl",
        ".zpl": "Zimpl",
        ".zs": "ZenScript",
        ".zsh": "Shell",
        ".zsh-theme": "Shell",
    }
