name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.13"
  UV_VERSION: "0.6.16"

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: |
          pip install uv==${{ env.UV_VERSION }}

      - name: Install deps
        run: |
          uv pip install --system --requirements python_coderunner/pyproject.toml

      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files

  tests:
    name: Run tests
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: |
          pip install uv==${{ env.UV_VERSION }}

      - name: Install deps
        run: |
          uv pip install --system --requirements python_coderunner/pyproject.toml

      - name: Run tests
        run: |
          cd python_coderunner
          pytest
